fix race condition #13
doitintl/secrets-init pull request #14
Opened 2021-07-29 17:58 UTC by aclowes

wait4 and cmd.wait would wait on the child process, and an error was thrown if wait4 got it first. Instead, remove the cmd.wait and use only wait4. 

Also:
- capture and exit with the child process return code
- don't sleep between wait4 calls, let wait4 block for us.

2021-10-20 06:44 UTC, alexei-led requested changes
@aclowes thank you for the PR. I would like to better understand these changes

2021-10-20 06:44 UTC, alexei-led commented on main.go
> +func run(ctx context.Context, provider secrets.Provider, commandSlice []string, childPid *int) error {
Please use `return` to return child PID from the function and not as a reference to the parameter.

2021-10-20 06:44 UTC, alexei-led commented on main.go
> +		pid, err := syscall.Wait4(-1, &status, 0, nil)
why to replace `syscall.WNOHANG` with `0`?

2021-10-20 06:44 UTC, alexei-led commented on main.go
>  		}
why non-blocking test removed? can you, please, explain

2021-10-21 17:05 UTC, aclowes commented on main.go
> +func run(ctx context.Context, provider secrets.Provider, commandSlice []string, childPid *int) error {
Changed. I used named return values; I'm not sure if this is appropriate.

2021-10-21 17:05 UTC, aclowes commented on main.go
> +		pid, err := syscall.Wait4(-1, &status, 0, nil)
WNOHANG returns immediately. Zero waits until there is a process to reap. This change makes the code more efficient, instead of running in a busy loop it waits for the next event.

2021-10-21 17:09 UTC, aclowes commented on main.go
>  		}
I removed the WaitGroup and context because we are no longer waiting for the child process in a separate routine - instead, all processes (the child and any grandchildren) are reaped in this loop.

2021-10-24 08:35 UTC, alexei-led commented on main.go
>  		}
ok

2021-10-25 17:24 UTC, aclowes commented
@alexei-led I've fixed the link error, would you please re-run the workflow? Thanks.

2021-10-27 12:51 UTC, merged