Add environment variable for all flags and envvar prefix
doitintl/secrets-init pull request #42
Opened 2024-01-08 20:06 UTC by albertrdixon

## What

- Add environment variable for `provider` flag
- Add environmetn variable for `google-project` flag
- Add optional environment variables format with `SECRETS_INIT` prefix

## Why

- Using secrets init for apps in GCP required setting the command line flag rather than the much easier (in kubernetes at least) environment variable flow
- Using a prefix for environment variables helps to avoid collision (in particular with `LOG_FORMAT`)

2024-02-05 20:02 UTC, sakomws commented
hey, @alexei-led help is appreciated with this PR review pls.

2024-05-13 07:48 UTC, alexei-led requested changes
Thank you for this PR. Please make sure all ENV variables are consistent: two ENV vars per parameter (one with prefix and another without)

2024-05-13 07:48 UTC, alexei-led commented on main.go
> +				EnvVars: []string{"SECRETS_INIT_SECRETS_PROVIDER"}
Please add a second ENV without prefix

2024-05-13 07:48 UTC, alexei-led commented on main.go
> +				EnvVars: []string{"SECRETS_INIT_GOOGLE_PROJECT"}
Please add a second ENV without a prefix, too.

2024-05-24 19:59 UTC, albertrdixon commented on main.go
> +				EnvVars: []string{"SECRETS_INIT_SECRETS_PROVIDER"}
https://github.com/doitintl/secrets-init/pull/42/commits/984ce661cee19e67362c170674a57b53c9348f75

2024-05-24 19:59 UTC, albertrdixon commented on main.go
> +				EnvVars: []string{"SECRETS_INIT_GOOGLE_PROJECT"}
https://github.com/doitintl/secrets-init/pull/42/commits/984ce661cee19e67362c170674a57b53c9348f75

2024-05-27 14:02 UTC, alexei-led approved these changes

2024-05-27 14:03 UTC, merged